### ISSUE TITLE
预览网站无法使用

### ISSUE THREAD

**Issue by Backupdown** [egdw/VR_justeasy_krpano_downloader#2]
十分感谢！
软件可以下载，但是预览网站无法使用（http://egdw.gitee.io/panorama_display/）

**Comment by egdw** [comment]
https://gitee.com/egdw/panorama_display

gitee pages官方功能已经下线，源码在这里

**Comment by egdw** [comment]
![image](https://github.com/user-attachments/assets/a317aed2-7b81-4fe1-a564-610bafffabb1)

**Comment by egdw** [comment]
https://egdw.github.io/VR_justeasy_krpano_downloader/panorama_display/
